include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
